apiVersion: v1
kind: Pod
metadata:
#  generateName: pod-network-loss-
  name: pod-network-loss
  namespace: litmus
spec:
  serviceAccountName: litmus-admin
  volumes:
    - name: cri-socket
      hostPath:
        path: /run/containerd/containerd.sock
  containers:
    - name: pod-network-loss
      image: localhost:5000/sinth-chaos-poc:latest
      imagePullPolicy: IfNotPresent
      command:
        - /sinth/sinth
#        - sleep
#        - infinity
      env:
        - name: NAMESPACE
          value: order-api-app
        - name: LABEL_SELECTOR
          value: app=order-api-app
        - name: NETWORK_INTERFACE
          value: eth0
        - name: NETEM_COMMANDS
          value: loss 100
        - name: SOCKET_PATH
          value: /run/containerd/containerd.sock
        - name: DESTINATION_IPS
          value: 142.250.219.142,20.76.201.171,20.236.44.162,20.112.250.133,20.231.239.246,20.70.246.20,10.96.84.111
      volumeMounts:
        - name: cri-socket
          mountPath: /run/containerd/containerd.sock
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
            - SYS_ADMIN
            - SYS_PTRACE
        privileged: true
        runAsUser: 0
  hostPID: true
